// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bbb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SIBClient is the client API for SIB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SIBClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type sIBClient struct {
	cc grpc.ClientConnInterface
}

func NewSIBClient(cc grpc.ClientConnInterface) SIBClient {
	return &sIBClient{cc}
}

func (c *sIBClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/aaa.bbb.SIB/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sIBClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/aaa.bbb.SIB/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SIBServer is the server API for SIB service.
// All implementations must embed UnimplementedSIBServer
// for forward compatibility
type SIBServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedSIBServer()
}

// UnimplementedSIBServer must be embedded to have forward compatible implementations.
type UnimplementedSIBServer struct {
}

func (UnimplementedSIBServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedSIBServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedSIBServer) mustEmbedUnimplementedSIBServer() {}

// UnsafeSIBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SIBServer will
// result in compilation errors.
type UnsafeSIBServer interface {
	mustEmbedUnimplementedSIBServer()
}

func RegisterSIBServer(s grpc.ServiceRegistrar, srv SIBServer) {
	s.RegisterService(&SIB_ServiceDesc, srv)
}

func _SIB_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SIBServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aaa.bbb.SIB/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SIBServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SIB_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SIBServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aaa.bbb.SIB/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SIBServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SIB_ServiceDesc is the grpc.ServiceDesc for SIB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SIB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aaa.bbb.SIB",
	HandlerType: (*SIBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _SIB_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _SIB_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SIB.proto",
}
